
title: Daniel Vera's CV
url: 'http://danielvera.org'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Daniel Vera
tagline: Computational Biologist
pic: dlv.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: daniel@danielvera.org
phone: 850 296 8372
#website: blog.webjeda.com #do not add http://
#linkedin: alandoe
github: dvera
twitter: '@dlv04c'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
